export const ACTION_TYPES = {
  // For notesReducer
  UPDATE_NOTES: "UPDATE_NOTES",
  ADD_NOTE: "ADD_NOTE",

  // For formReducer
  SET_TITLE: "SET_TITLE",
  SET_DETAILS: "SET_DETAILS",
  SET_CATEGORY: "SET_CATEGORY",
  SET_TITLE_ERROR: "SET_TITLE_ERROR",
  SET_DETAIL_ERROR: "SET_DETAIL_ERROR",
};
